### ISSUE TITLE
登录后提示www2端喜马拉雅接口内部异常

### ISSUE THREAD

**Issue by 2222221029** [844704781/ximalaya_downloader#13]
www2端喜马拉雅接口内部异常 { reqId: 'a47c4486-144004060', ret: 1001, msg: '系统 繁忙，请稍后再试!' }
大佬你好，现在登录后提示这个错误，目前只有mac端可以使用，请问可以修复一下www2端吗

**Comment by 844704781** [comment]
1.0.1版本已修复
