### ISSUE TITLE
运行失败，报错：TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///XXX/config.json" needs an import assertion of type "json"

### ISSUE THREAD

**Issue by shanyan-wcx** [844704781/ximalaya_downloader#5]
需要在config.js中的import defaultConfig from "../config.json"后面添加 assert { type: "json" }来消除报错。

**Comment by 844704781** [comment]
是什么环境

**Comment by shanyan-wcx** [comment]
就是win11安装了node v18

**Comment by 844704781** [comment]
> 就是win11安装了node v18

是否可以提交个fix的pr，我这边合并一下

**Comment by shanyan-wcx** [comment]
> > 就是win11安装了node v18
> 
> 是否可以提交个fix的pr，我这边合并一下

这玩意它提示说导入json是node的实验功能，可能随时更改，然后我另一台电脑上装的是node22，就不能用assert了，得换成with才行，这样不同版本语法不一样挺麻烦的，我觉得是不是改成使用fs来读取配置比较好？

**Comment by shanyan-wcx** [comment]
我看了一下，defaultConfig似乎是多余的，删掉也不影响使用，反而能避免语法问题。那我就提交个删掉defaultConfig的pr吧

**Comment by 844704781** [comment]
> 我看了一下，defaultConfig似乎是多余的，删掉也不影响使用，反而能避免语法问题。那我就提交个删掉defaultConfig的pr吧

好的， 是否可以测下编译的版本

**Comment by shanyan-wcx** [comment]
测了，编译完没问题

**Comment by 844704781** [comment]
> 测了，编译完没问题

感谢
